logging:
  pattern:
    console: "%clr(> %d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%-5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"


spring:
  rabbitmq:
    #    default addresses: http://localhost:5672
    addresses: localhost:5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual



#  in case you are running rabbitmq on a different server or using different credentials,
#  you an change this configuration

#spring:
#  rabbitmq:
#    host: 192.15.16.193
#    port: 5672
#    username: dev
#    password: mypassword123
